[package]
name = "rustboy"
version = "0.1.0"
authors = ["val500 <varun.valada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queue = "0.3"
sdl2 = "0.34"
spin_sleep = "1.0.0"
byteorder = "1.4.3"